import { Routes } from '@angular/router';
import { WorkspaceRouteComponent } from './workspace-route.component';

export const appRoutes: Routes = [
  { path: '', pathMatch: 'full', redirectTo: 'visao-geral' },
  { path: 'auth/callback', component: WorkspaceRouteComponent, data: { view: 'overview' } },
  { path: 'visao-geral', component: WorkspaceRouteComponent, data: { view: 'overview' } },
  { path: 'contas', pathMatch: 'full', component: WorkspaceRouteComponent, data: { view: 'accounts' } },
  { path: 'contas/nova', component: WorkspaceRouteComponent, data: { view: 'accounts', action: 'create' } },
  { path: 'contas/:id/editar', component: WorkspaceRouteComponent, data: { view: 'accounts', action: 'edit' } },
  { path: 'cartoes', pathMatch: 'full', component: WorkspaceRouteComponent, data: { view: 'cards' } },
  { path: 'cartoes/novo', component: WorkspaceRouteComponent, data: { view: 'cards', action: 'create' } },
  { path: 'cartoes/parcelamentos/nova', component: WorkspaceRouteComponent, data: { view: 'cards', action: 'installment' } },
  { path: 'cartoes/:id/editar', component: WorkspaceRouteComponent, data: { view: 'cards', action: 'edit' } },
  { path: 'recorrencias', pathMatch: 'full', component: WorkspaceRouteComponent, data: { view: 'recurrences' } },
  { path: 'recorrencias/nova', component: WorkspaceRouteComponent, data: { view: 'recurrences', action: 'create' } },
  { path: 'orcamento', pathMatch: 'full', component: WorkspaceRouteComponent, data: { view: 'budget' } },
  { path: 'orcamento/novo-limite', component: WorkspaceRouteComponent, data: { view: 'budget', action: 'create' } },
  { path: 'metas', pathMatch: 'full', component: WorkspaceRouteComponent, data: { view: 'goals' } },
  { path: 'metas/nova', component: WorkspaceRouteComponent, data: { view: 'goals', action: 'create' } },
  { path: 'lancamentos', pathMatch: 'full', component: WorkspaceRouteComponent, data: { view: 'transactions' } },
  { path: 'lancamentos/novo', component: WorkspaceRouteComponent, data: { view: 'transactions', action: 'create' } },
  { path: 'lancamentos/:id/editar', component: WorkspaceRouteComponent, data: { view: 'transactions', action: 'edit' } },
  { path: 'transferencias', pathMatch: 'full', component: WorkspaceRouteComponent, data: { view: 'transfers' } },
  { path: 'transferencias/nova', component: WorkspaceRouteComponent, data: { view: 'transfers', action: 'create' } },
  { path: 'importacoes', pathMatch: 'full', component: WorkspaceRouteComponent, data: { view: 'imports' } },
  { path: 'importacoes/nova', component: WorkspaceRouteComponent, data: { view: 'imports', action: 'create' } },
  { path: 'categorias', pathMatch: 'full', component: WorkspaceRouteComponent, data: { view: 'categories' } },
  { path: 'categorias/nova', component: WorkspaceRouteComponent, data: { view: 'categories', action: 'create' } },
  { path: 'categorias/subcategorias/:id/editar', component: WorkspaceRouteComponent, data: { view: 'categories', action: 'edit-subcategory' } },
  { path: 'categorias/subcategorias/nova', component: WorkspaceRouteComponent, data: { view: 'categories', action: 'create-subcategory' } },
  { path: 'categorias/:id/editar', component: WorkspaceRouteComponent, data: { view: 'categories', action: 'edit' } },
  { path: 'configuracoes/perfil', component: WorkspaceRouteComponent, data: { view: 'profile' } },
  { path: 'configuracoes/grupo', component: WorkspaceRouteComponent, data: { view: 'group' } },
  { path: '**', redirectTo: 'visao-geral' },
];
