export type CardNetwork = 'VISA' | 'MASTERCARD' | 'ELO' | 'AMERICAN_EXPRESS' | 'HIPERCARD' | 'DINERS_CLUB' | 'DISCOVER' | 'JCB' | 'UNIONPAY' | 'MAESTRO' | 'OTHER';

type BrandOption = { name: string; logoUrl: string };

const iconUrl = (slug: string) => `https://cdn.jsdelivr.net/npm/simple-icons@v16/icons/${slug}.svg`;

export const brazilianBanks: readonly BrandOption[] = [
  { name: 'Carteira (conta não bancária)', logoUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="%235b5bd6"%3E%3Cpath d="M20 7V6a2 2 0 0 0-2-2H5a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h15a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2Zm-2-1v1H5a1 1 0 0 1 0-2h13ZM5 18a1 1 0 0 1-1-1V8.82A3 3 0 0 0 5 9h15v9H5Zm11-3a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z"/%3E%3C/svg%3E' },
  { name: 'ABC Brasil', logoUrl: '/assets/banks/bank-001.svg' },
  { name: 'Ailos', logoUrl: '/assets/banks/bank-002.svg' },
  { name: 'Almah Conta', logoUrl: '/assets/banks/bank-003.svg' },
  { name: 'Artta', logoUrl: '/assets/banks/bank-004.svg' },
  { name: 'Asaas IP S.A', logoUrl: '/assets/banks/bank-005.svg' },
  { name: 'BK Bank', logoUrl: '/assets/banks/bank-006.svg' },
  { name: 'BNP Paripas', logoUrl: '/assets/banks/bank-007.svg' },
  { name: 'BRB - Banco de Brasilia', logoUrl: '/assets/banks/bank-008.svg' },
  { name: 'Banco do Brasil S.A', logoUrl: '/assets/banks/bank-009.svg' },
  { name: 'Banco Arbi', logoUrl: '/assets/banks/bank-010.svg' },
  { name: 'Banco BS2 S.A', logoUrl: '/assets/banks/bank-011.svg' },
  { name: 'Banco BTG Pacutal', logoUrl: '/assets/banks/bank-012.svg' },
  { name: 'Banco C6 S.A', logoUrl: '/assets/banks/bank-013.svg' },
  { name: 'Banco Inter S.A', logoUrl: '/assets/banks/bank-014.svg' },
  { name: 'Banco Mercantil do Brasil S.A', logoUrl: '/assets/banks/bank-015.svg' },
  { name: 'Banco Pan', logoUrl: '/assets/banks/bank-016.svg' },
  { name: 'Banco Paulista', logoUrl: '/assets/banks/bank-017.svg' },
  { name: 'Banco Pine', logoUrl: '/assets/banks/bank-018.svg' },
  { name: 'Banco da Amazônia S.A', logoUrl: '/assets/banks/bank-019.svg' },
  { name: 'Banco do Estado do Espirito Santo', logoUrl: '/assets/banks/bank-020.svg' },
  { name: 'Banco BMG', logoUrl: '/assets/banks/bank-021.svg' },
  { name: 'Banco BMP', logoUrl: '/assets/banks/bank-022.svg' },
  { name: 'Banco Daycoval', logoUrl: '/assets/banks/bank-023.svg' },
  { name: 'Banco Industrial do Brasil S.A', logoUrl: '/assets/banks/bank-024.svg' },
  { name: 'Banco Original S.A', logoUrl: '/assets/banks/bank-025.svg' },
  { name: 'Banco Rendimento', logoUrl: '/assets/banks/bank-026.svg' },
  { name: 'Banco Safra S.A', logoUrl: '/assets/banks/bank-027.svg' },
  { name: 'Banco Santander Brasil S.A', logoUrl: '/assets/banks/bank-028.svg' },
  { name: 'Banco Sofisa', logoUrl: '/assets/banks/bank-029.svg' },
  { name: 'Banco Topazio', logoUrl: '/assets/banks/bank-030.svg' },
  { name: 'Banco Triângulo - Tribanco', logoUrl: '/assets/banks/bank-031.svg' },
  { name: 'Banco Votorantim', logoUrl: '/assets/banks/bank-032.svg' },
  { name: 'Banco do Estado do Para', logoUrl: '/assets/banks/bank-033.svg' },
  { name: 'Banco do Estado do Sergipe', logoUrl: '/assets/banks/bank-034.svg' },
  { name: 'Banco do Nordeste do Brasil S.A', logoUrl: '/assets/banks/bank-035.svg' },
  { name: 'Bank of America', logoUrl: '/assets/banks/bank-036.svg' },
  { name: 'Banrisul', logoUrl: '/assets/banks/bank-037.svg' },
  { name: 'Bees Bank', logoUrl: '/assets/banks/bank-038.svg' },
  { name: 'Bradesco S.A', logoUrl: '/assets/banks/bank-039.svg' },
  { name: 'Caixa Econômica Federal', logoUrl: '/assets/banks/bank-040.svg' },
  { name: 'Capitual', logoUrl: '/assets/banks/bank-041.svg' },
  { name: 'Conta Simples Soluções em Pagamentos', logoUrl: '/assets/banks/bank-042.svg' },
  { name: 'Contbank', logoUrl: '/assets/banks/bank-043.svg' },
  { name: 'Cora Sociedade Credito Direto S.A', logoUrl: '/assets/banks/bank-044.svg' },
  { name: 'Credisis', logoUrl: '/assets/banks/bank-045.svg' },
  { name: 'Cresol', logoUrl: '/assets/banks/bank-046.svg' },
  { name: 'Dock', logoUrl: '/assets/banks/bank-047.svg' },
  { name: 'DuePay', logoUrl: '/assets/banks/bank-048.svg' },
  { name: 'Efí - Gerencianet', logoUrl: '/assets/banks/bank-049.svg' },
  { name: 'Grafeno', logoUrl: '/assets/banks/bank-050.svg' },
  { name: 'Ifood Pago', logoUrl: '/assets/banks/bank-051.svg' },
  { name: 'InfinitePay', logoUrl: '/assets/banks/bank-052.svg' },
  { name: 'Ip4y', logoUrl: '/assets/banks/bank-053.svg' },
  { name: 'Itaú Unibanco S.A', logoUrl: '/assets/banks/bank-054.svg' },
  { name: 'Iugo', logoUrl: '/assets/banks/bank-055.svg' },
  { name: 'Lets Bank S.A', logoUrl: '/assets/banks/bank-056.svg' },
  { name: 'Linker', logoUrl: '/assets/banks/bank-057.svg' },
  { name: 'MUFG', logoUrl: '/assets/banks/bank-058.svg' },
  { name: 'MagaluPay', logoUrl: '/assets/banks/bank-059.svg' },
  { name: 'Mercado Pago', logoUrl: '/assets/banks/bank-060.svg' },
  { name: 'ModoBank', logoUrl: '/assets/banks/bank-061.svg' },
  { name: 'Multiplo Bank', logoUrl: '/assets/banks/bank-062.svg' },
  { name: 'Neon', logoUrl: '/assets/banks/bank-063.svg' },
  { name: 'Nu Pagamentos S.A', logoUrl: '/assets/banks/bank-064.svg' },
  { name: 'Omie.Cash', logoUrl: '/assets/banks/bank-065.svg' },
  { name: 'Omni', logoUrl: '/assets/banks/bank-066.svg' },
  { name: 'OrionPay', logoUrl: '/assets/banks/bank-067.svg' },
  { name: 'PagSeguro Internet S.A', logoUrl: '/assets/banks/bank-068.svg' },
  { name: 'PayCash', logoUrl: '/assets/banks/bank-069.svg' },
  { name: 'PicPay', logoUrl: '/assets/banks/bank-070.svg' },
  { name: 'PinBank', logoUrl: '/assets/banks/bank-071.svg' },
  { name: 'Quality Digital Bank', logoUrl: '/assets/banks/bank-072.svg' },
  { name: 'RecargaPay', logoUrl: '/assets/banks/bank-073.svg' },
  { name: 'Sicoob', logoUrl: '/assets/banks/bank-074.svg' },
  { name: 'Sicredi', logoUrl: '/assets/banks/bank-075.svg' },
  { name: 'Sisprime', logoUrl: '/assets/banks/bank-076.svg' },
  { name: 'Squid Soluções Financeiras', logoUrl: '/assets/banks/bank-077.svg' },
  { name: 'StarBank', logoUrl: '/assets/banks/bank-078.svg' },
  { name: 'Stone Pagamentos S.A', logoUrl: '/assets/banks/bank-079.svg' },
  { name: 'Sulcredi', logoUrl: '/assets/banks/bank-080.svg' },
  { name: 'Transfera', logoUrl: '/assets/banks/bank-081.svg' },
  { name: 'Unicred', logoUrl: '/assets/banks/bank-082.svg' },
  { name: 'Uniprime', logoUrl: '/assets/banks/bank-083.svg' },
  { name: 'UzziPay', logoUrl: '/assets/banks/bank-084.svg' },
  { name: 'XP Investimentos', logoUrl: '/assets/banks/bank-085.svg' },
  { name: 'Zemo Bank', logoUrl: '/assets/banks/bank-086.svg' },
];

const legacyBankNames: Readonly<Record<string, string>> = {
  'Banco do Brasil': 'Banco do Brasil S.A', Bradesco: 'Bradesco S.A', Caixa: 'Caixa Econômica Federal',
  Itaú: 'Itaú Unibanco S.A', Santander: 'Banco Santander Brasil S.A', Nubank: 'Nu Pagamentos S.A',
  Inter: 'Banco Inter S.A', 'C6 Bank': 'Banco C6 S.A', 'BTG Pactual': 'Banco BTG Pacutal',
  Safra: 'Banco Safra S.A', 'Banco PAN': 'Banco Pan', PagBank: 'PagSeguro Internet S.A',
};

/** Resolves historic display names too, so pre-existing records no longer request remote images. */
export const bankLogoUrlFor = (bankName?: string, fallback?: string) => {
  const canonicalName = bankName ? legacyBankNames[bankName] ?? bankName : undefined;
  return brazilianBanks.find((bank) => bank.name === canonicalName)?.logoUrl
    ?? (fallback?.startsWith('/assets/') ? fallback : undefined);
};

export const cardNetworks: Readonly<Record<CardNetwork, BrandOption>> = {
  VISA: { name: 'Visa', logoUrl: iconUrl('visa') }, MASTERCARD: { name: 'Mastercard', logoUrl: iconUrl('mastercard') },
  ELO: { name: 'Elo', logoUrl: iconUrl('elo') }, AMERICAN_EXPRESS: { name: 'American Express', logoUrl: iconUrl('americanexpress') },
  HIPERCARD: { name: 'Hipercard', logoUrl: iconUrl('hipercard') }, DINERS_CLUB: { name: 'Diners Club', logoUrl: iconUrl('dinersclub') },
  DISCOVER: { name: 'Discover', logoUrl: iconUrl('discover') }, JCB: { name: 'JCB', logoUrl: iconUrl('jcb') },
  UNIONPAY: { name: 'UnionPay', logoUrl: iconUrl('unionpay') }, MAESTRO: { name: 'Maestro', logoUrl: iconUrl('maestro') },
  OTHER: { name: 'Outra bandeira', logoUrl: '' },
};
